### ISSUE TITLE
Is there anyway to run the code with emulators?

### ISSUE THREAD

**Issue by philipvu30** [sbis04/flutter_docker#1]
Hi,

Thank you for your amazing work.
I just have a question that how I could run the code with an emulator?

**Comment by sbis04** [comment]
Hi, you can take a look at this article for some help: [Run Android Emulator on Docker](https://medium.com/@AndreSand/android-emulator-on-docker-container-f20c49b129ef)

This article is a bit old, so you might have some issues.

**Comment by philipvu30** [comment]
Thanks for the information @sbis04. I appreciate your help :)
