### ISSUE TITLE
How to set up docker environment via IntelliJ Idea?

### ISSUE THREAD

**Issue by ValeriusGC** [sbis04/flutter_docker#2]
Hi there!
Your article about [docker in VS Code](https://blog.codemagic.io/how-to-dockerize-flutter-apps/) is awful.
I tried do the same in IJI, but stucked in it.
I added docker plugin, made images and containers, but no idea, how make environment in IJI? In another words, i can not emulate flutter project in IJI via docker.
![Screenshot from 2020-05-07 11-56-47](https://user-images.githubusercontent.com/3320861/81263936-03987180-905a-11ea-806b-c852fe2427be.png)

Can you give me some help?

**Comment by sbis04** [comment]
Hi, you can use an officially maintained Docker Image for Flutter, like this one: [cirrusci/flutter](https://hub.docker.com/r/cirrusci/flutter)

In **IntelliJ** you do not have any `devcontainer.json` file like in VS Code, but you can define the configurations in IntelliJ also. This official guide can help you: https://www.jetbrains.com/help/idea/docker.html#run-containers

For running the flutter app on an **Android emulator**, you can take a look at this article: [Run Android Emulator on Docker](https://medium.com/@AndreSand/android-emulator-on-docker-container-f20c49b129ef). But this article is a bit old, so there might be some issues.

If you want to run the app on a **physical device**, then you can just follow the method here: https://blog.codemagic.io/how-to-dockerize-flutter-apps/#for-macos-and-windows-users
